- name: deploy app
  hosts: app
  tags: deploy-tag
  tasks:
    - name: fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
