---
- name: install mongodb 3.2
  hosts: all
  become: true
  tasks:
    - name: add apt key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: add apt repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: install mongodb package
      apt:
        name: mongodb-org
        allow_unauthenticated: yes
        state: present

    - name: configure service supervisor
      systemd:
        name: mongod
        enabled: yes
        