---
- name: configure hosts & deploy application # <-- Словесное описание сценария(name)
  hosts: all # <-- Для каких хостов будут выполняться описанные ниже таски (hosts)
  #debugger: on_failed
  vars:
    mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars
    db_host: 10.128.0.4
  tasks: # <-- Блок тасков (заданий), которые будут выполняться для данных хостов
    - name: change mongo config file
      become: true # <-- Выполнить задание от root
      template:
        src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
        dest: /etc/mongod.conf # <-- Путь на удаленном хосте
        mode: 0644 # <-- Права на файл, которые нужно установить
      tags: db-tag
      notify: restart mongod
    - name: add unit file for puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma
    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag
    - name: add config for db connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag
    - name: install git
      become: true
      apt: name=git update_cache=yes state=latest
      tags: git-tag
    - name: fetch the latest version of application code
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag
      notify: reload puma
    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle
      tags: deploy-tag

  handlers: # <-- Добавим блок handlers и задачу
    - name: restart mongod
      become: true
      service: name=mongod state=restarted
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
